// frontend/FormatDisplay.jsx
import React from 'react';
import { Card, Row, Col, Typography, Tag, Descriptions, Space, Divider } from 'antd';
import { FileTextOutlined, SettingOutlined, FontSizeOutlined } from '@ant-design/icons';

const { Title, Text } = Typography;

const FormatDisplay = ({ formatData }) => {
  if (!formatData || !formatData.success) {
    return (
      <Card>
        <Text type="danger">格式识别失败</Text>
      </Card>
    );
  }

  const { display_data } = formatData;

  // 渲染页面设置
  const renderPageSettings = () => {
    const settings = display_data.page_settings;
    if (!settings) return null;

    const basicItems = settings.items.filter(item => item.category === 'basic');
    const marginItems = settings.items.filter(item => item.category === 'margins');

    return (
      <Card 
        title={
          <Space>
            <SettingOutlined />
            <span>{settings.title}</span>
          </Space>
        }
        style={{ marginBottom: 16 }}
      >
        <Descriptions bordered size="small" column={2}>
          {basicItems.map((item, index) => (
            <Descriptions.Item key={index} label={item.label}>
              <Tag color="blue">{item.value}</Tag>
            </Descriptions.Item>
          ))}
        </Descriptions>
        
        <Divider orientation="left">页边距设置</Divider>
        
        <Row gutter={[16, 16]}>
          {marginItems.map((item, index) => (
            <Col key={index} xs={24} sm={12} md={6}>
              <Card size="small" style={{ textAlign: 'center' }}>
                <Text type="secondary">{item.label}</Text>
                <br />
                <Text strong style={{ fontSize: 16 }}>{item.value}</Text>
              </Card>
            </Col>
          ))}
        </Row>
      </Card>
    );
  };

  // 渲染样式设置
  const renderStyles = () => {
    const styles = display_data.styles;
    if (!styles || styles.length === 0) return null;

    return (
      <Card 
        title={
          <Space>
            <FontSizeOutlined />
            <span>样式设置</span>
          </Space>
        }
        style={{ marginBottom: 16 }}
      >
        <Row gutter={[16, 16]}>
          {styles.map((style, index) => (
            <Col key={index} xs={24} md={12} lg={8}>
              <Card 
                type="inner" 
                title={style.name}
                extra={<Tag color="green">{style.key}</Tag>}
              >
                <Space direction="vertical" style={{ width: '100%' }}>
                  {/* 字体设置 */}
                  <div>
                    <Text strong>字体设置</Text>
                    <Descriptions size="small" column={1} style={{ marginTop: 8 }}>
                      {style.font.map((item, idx) => (
                        <Descriptions.Item key={idx} label={item.label}>
                          {item.value}
                        </Descriptions.Item>
                      ))}
                    </Descriptions>
                  </div>

                  {/* 段落设置 */}
                  <div>
                    <Text strong>段落设置</Text>
                    <Descriptions size="small" column={1} style={{ marginTop: 8 }}>
                      {style.paragraph.map((item, idx) => (
                        <Descriptions.Item key={idx} label={item.label}>
                          {item.value}
                        </Descriptions.Item>
                      ))}
                    </Descriptions>
                  </div>
                </Space>
              </Card>
            </Col>
          ))}
        </Row>
      </Card>
    );
  };

  // 渲染文档结构
  const renderDocumentStructure = () => {
    const structure = display_data.document_structure;
    if (!structure || !structure.items || structure.items.length === 0) return null;

    return (
      <Card 
        title={
          <Space>
            <FileTextOutlined />
            <span>{structure.title}</span>
          </Space>
        }
      >
        <Descriptions bordered size="small">
          {structure.items.map((item, index) => (
            <Descriptions.Item key={index} label={item.label} span={3}>
              <Tag color={item.category === 'toc' ? 'purple' : 'orange'}>
                {item.value}
              </Tag>
            </Descriptions.Item>
          ))}
        </Descriptions>
      </Card>
    );
  };

  return (
    <div style={{ padding: 24 }}>
      <Title level={2}>文档格式要求</Title>
      <Text type="secondary" style={{ marginBottom: 24, display: 'block' }}>
        以下是AI智能识别的格式配置，请仔细检查是否符合您的要求
      </Text>
      
      {renderPageSettings()}
      {renderStyles()}
      {renderDocumentStructure()}
    </div>
  );
};

export default FormatDisplay;

// frontend/FormatDisplay.vue
<template>
  <div class="format-display">
    <el-card class="header-card">
      <h1>文档格式要求</h1>
      <p class="subtitle">AI智能识别的格式配置</p>
    </el-card>

    <div v-if="!formatData || !formatData.success" class="error-container">
      <el-alert title="格式识别失败" type="error" :closable="false" />
    </div>

    <template v-else>
      <!-- 页面设置 -->
      <el-card v-if="displayData.page_settings" class="section-card">
        <template #header>
          <div class="card-header">
            <i class="el-icon-setting"></i>
            <span>{{ displayData.page_settings.title }}</span>
          </div>
        </template>

        <!-- 基本设置 -->
        <el-row :gutter="20">
          <el-col 
            v-for="item in basicSettings" 
            :key="item.label"
            :xs="24" :sm="12" :md="8"
          >
            <div class="setting-item">
              <span class="label">{{ item.label }}:</span>
              <el-tag type="info">{{ item.value }}</el-tag>
            </div>
          </el-col>
        </el-row>

        <!-- 页边距设置 -->
        <el-divider content-position="left">页边距设置</el-divider>
        <el-row :gutter="20">
          <el-col 
            v-for="item in marginSettings" 
            :key="item.label"
            :xs="12" :sm="6"
          >
            <el-card shadow="hover" class="margin-card">
              <div class="margin-label">{{ item.label }}</div>
              <div class="margin-value">{{ item.value }}</div>
            </el-card>
          </el-col>
        </el-row>
      </el-card>

      <!-- 样式设置 -->
      <el-card v-if="displayData.styles" class="section-card">
        <template #header>
          <div class="card-header">
            <i class="el-icon-document"></i>
            <span>样式设置</span>
          </div>
        </template>

        <el-collapse v-model="activeStyles">
          <el-collapse-item 
            v-for="(style, index) in displayData.styles" 
            :key="style.key"
            :title="style.name"
            :name="index"
          >
            <el-row :gutter="20">
              <!-- 字体设置 -->
              <el-col :xs="24" :md="12">
                <div class="style-group">
                  <h4>字体设置</h4>
                  <el-descriptions :column="1" size="small" border>
                    <el-descriptions-item 
                      v-for="item in style.font" 
                      :key="item.label"
                      :label="item.label"
                    >
                      <span :class="{ 'font-bold': item.value === '是' }">
                        {{ item.value }}
                      </span>
                    </el-descriptions-item>
                  </el-descriptions>
                </div>
              </el-col>

              <!-- 段落设置 -->
              <el-col :xs="24" :md="12">
                <div class="style-group">
                  <h4>段落设置</h4>
                  <el-descriptions :column="1" size="small" border>
                    <el-descriptions-item 
                      v-for="item in style.paragraph" 
                      :key="item.label"
                      :label="item.label"
                    >
                      {{ item.value }}
                    </el-descriptions-item>
                  </el-descriptions>
                </div>
              </el-col>
            </el-row>
          </el-collapse-item>
        </el-collapse>
      </el-card>

      <!-- 文档结构 -->
      <el-card 
        v-if="displayData.document_structure && displayData.document_structure.items.length > 0" 
        class="section-card"
      >
        <template #header>
          <div class="card-header">
            <i class="el-icon-files"></i>
            <span>{{ displayData.document_structure.title }}</span>
          </div>
        </template>

        <el-table :data="displayData.document_structure.items" stripe>
          <el-table-column prop="label" label="设置项" width="200" />
          <el-table-column prop="value" label="值">
            <template #default="{ row }">
              <el-tag :type="getTagType(row.category)">
                {{ row.value }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="category" label="类别" width="150">
            <template #default="{ row }">
              <span class="category-label">{{ getCategoryLabel(row.category) }}</span>
            </template>
          </el-table-column>
        </el-table>
      </el-card>
    </template>
  </div>
</template>

<script>
export default {
  name: 'FormatDisplay',
  props: {
    formatData: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      activeStyles: [0] // 默认展开第一个样式
    };
  },
  computed: {
    displayData() {
      return this.formatData?.display_data || {};
    },
    basicSettings() {
      return this.displayData.page_settings?.items.filter(item => item.category === 'basic') || [];
    },
    marginSettings() {
      return this.displayData.page_settings?.items.filter(item => item.category === 'margins') || [];
    }
  },
  methods: {
    getTagType(category) {
      const typeMap = {
        'toc': 'primary',
        'numbering': 'warning',
        'default': 'info'
      };
      return typeMap[category] || typeMap.default;
    },
    getCategoryLabel(category) {
      const labelMap = {
        'toc': '目录设置',
        'numbering': '页码设置'
      };
      return labelMap[category] || category;
    }
  }
};
</script>

<style scoped>
.format-display {
  padding: 20px;
  background-color: #f5f7fa;
  min-height: 100vh;
}

.header-card {
  margin-bottom: 20px;
  text-align: center;
}

.header-card h1 {
  margin: 0 0 10px 0;
  color: #303133;
}

.subtitle {
  color: #909399;
  margin: 0;
}

.section-card {
  margin-bottom: 20px;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 18px;
  font-weight: 600;
}

.card-header i {
  font-size: 20px;
  color: #409eff;
}

.setting-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px;
  background: #f4f4f5;
  border-radius: 4px;
  margin-bottom: 10px;
}

.setting-item .label {
  color: #606266;
  font-weight: 500;
}

.margin-card {
  text-align: center;
  cursor: pointer;
  transition: transform 0.2s;
}

.margin-card:hover {
  transform: translateY(-2px);
}

.margin-label {
  color: #909399;
  font-size: 14px;
  margin-bottom: 8px;
}

.margin-value {
  color: #303133;
  font-size: 18px;
  font-weight: 600;
}

.style-group {
  margin-bottom: 20px;
}

.style-group h4 {
  margin: 0 0 10px 0;
  color: #606266;
}

.font-bold {
  font-weight: 600;
  color: #409eff;
}

.category-label {
  font-size: 12px;
  color: #909399;
  text-transform: uppercase;
}

.error-container {
  padding: 40px;
  text-align: center;
}

/deep/ .el-collapse-item__header {
  font-size: 16px;
  font-weight: 600;
}

/deep/ .el-descriptions__label {
  width: 120px;
}
</style>
